nf-core/proteomicslfq

- .github/workflows/main.yml
- .travis.yml
- conf/test.config
- main.nf
Adds a first, not yet fully running version.
> First version with CI

- .github/workflows/main.yml
- conf/test.config
- main.nf
- nextflow.config
General fixes.
There was a recent change that broke the pipeline with Percolator. We need to introduce tests for this!
> [Fix] general

- .gitignore
- main.nf
Such that logs are part of the results.
> Add more logging to the results.

- bin/scrape_software_versions.py
- main.nf
I'm missing `msstats_plfq.R` for the software versions. How do we fetch the version number for this?
> [FEATURE] Software versions

- README.md
- bin/scrape_software_versions.py
- conf/test.config
- docs/troubleshooting.md
- docs/usage.md
- nextflow.config
Just a few random comet parameters. I guess we should add a level in the documentation for the respective search engines, or else the documentation will just be a mess.
But @jpfeuffer you know best which parameters you want to expose, so I'll stop adding parameters for now :)
> [FEATURE] Some random cleanups & a few comet parameters

- conf/test.config
> Test URLS??

- Dockerfile
- bin/ptxqc.R
- environment.yml
- main.nf
This will add a quality control report with ptxqc.
In theory, this needs the OpenMS nightlies again for full support but it works already.
> [Feature] ptxqc

- .github/workflows/awstest.yml
- conf/test_full.config
- nextflow.config
this adds another GitHub action to test on bigger data from PRIDE.
> [FEATURE] Add aws test on PRIDE data.

- .github/workflows/ci.yml
> [FIX] Use a different tower token for the non-AWS tests

- bin/parse_sdrf.py
- main.nf
- nextflow.config
updated parse script. swith to 'path' for the first inputs to allow for URIs. add some more params
> [FEATURE] Finish support reading of PRIDE SDRF 

- main.nf
> [FIX] forgot enzyme

- main.nf
- nextflow.config
Allows specification of an optional root folder, where the already downloaded input files are located (matching to the filenames in the SDRF)
> [Feature] sdrf local

- main.nf
- nextflow.config
> Change the process name and add lsf support

- bin/msstats_plfq.R
> Remove NA proteins from volcano plots

- tools/README.md
- tools/interactive_msstats/GroupComparisonPlots.R
- tools/interactive_msstats/MsstatsInteractive.Rmd
For collecting useful downstream scripts.
> add a tools folder

- environment.yml
> sdrf-pipelines -> 0.0.4

- nextflow.config
> Minor changes in the default parameters 

- main.nf
instead of random UUID, use hash of filepath
fixes #43
> [FIX] caching and resume

- conf/big-cluster.config
- conf/big-nodes.config
> included big-cluster config

- main.nf
- nextflow.config
in case the (for Comet) incompatible ppm unit was used.
> Use guessing rule to convert from ppm frag_tol to Comet's bin_tol

- main.nf
- nextflow.config
Since sometimes TRFP misses to pick
> allow additional openms peak picking

- docs/usage.md
- main.nf
- nextflow.config
Let's you overwrite the input type in the sdrf for local files.
> [Feature] local input type

- docs/usage.md
- environment.yml
- main.nf
- nextflow.config
- tools/search_engine_scores/visualize_search_engine_scores.py
This adds support for combining results of multiple search engines via ConsensusID.
This will need nightly OpenMS versions. I am currently implementing stuff on the OpenMS side
for this.
Just put it here for comments.
> [Feature] multiple search engines

- environment.yml
- main.nf
This was a regression after adding ConsensusID. Unfortunately, I still do not have a small Phospho data set for CI.
> [FIX] Switch scores before luciphor

- conf/test.config
- conf/test_full.config
- conf/test_localize.config
- main.nf
- nextflow.config
- nextflow_schema.json
fixes #79 
And fixes some param documentation errors.
> [FEATURE] Use input parameter and decide mode based on extension.

- .github/workflows/awstest.yml
> fix awstest

- environment.yml
This is to trigger a new container build with the new nightly version.
> Try new mzTab

- bin/msstats_plfq.R
- main.nf
> try adding the MSstats output parser again

- .github/workflows/ci.yml
- conf/base.config
- conf/test_speccount.config
- main.nf
- nextflow.config
- nextflow_schema.json
> Minor changes added to the pipeline

- .github/workflows/awsfulltest.yml
- .github/workflows/awstest.yml
- README.md
- conf/base.config
- docs/README.md
- docs/output.md
- docs/usage.md
- environment.yml
- main.nf
> Fix openms+thirdparty versions

- environment.yml
- main.nf
- nextflow.config
- nextflow_schema.json
> [FEATURE] Bump to OpenMS 2.7 dev version with speed improvements and new alignment method

- main.nf
fixes #107 
You can't do it in the conversion process since you cannot update the tsv file one by one.
I would love to use groovy or something to not spawn another process but I just cannot make it work.
> add step to convert raw to mzml in experimental design

- main.nf
Very minor. Also fixes a little bug.
> Better encapsulation of renaming logic

- environment.yml
- main.nf
Adds a tsv output for feature quant for *manual* statistical evaluation with Triqler.
After testing, we can add an automated triqler step.
> [FEATURE] Add triqler output

- CHANGELOG.md
- conf/test.config
- main.nf
- nextflow.config
- nextflow_schema.json
Adds decoys when triqler is enabled.
> [Feature] Triqler output with decoys

- environment.yml
> change sdrf version -> 0.0.10

- lib/Checks.groovy
- lib/Completion.groovy
- lib/Headers.groovy
- lib/Schema.groovy
- main.nf
Based on the work of @drpatelh 
Probably comes with base nextflow or a plugin soon, but it is nice to have and was not any work at all.
> [FEATURE] autogenerate help from the json schema

- conf/base.config
- environment.yml
- main.nf
- nextflow.config
- nextflow_schema.json
> PeptideIndexer error fixed. 

- main.nf
- nextflow.config
- nextflow_schema.json
Some changes regarding decoy DB handling and error reporting.
> [FEATURE] More decoy DB options + fixes + error handling

- environment.yml
- main.nf
> [Fix] enzymes var

- main.nf
Now I put it into a channel. A global variable did not really work.
> [Fix] enzyme bug in decoy DB

- main.nf
The last PR broke something when not using SDRFs. This combination is not tested yet.
> [Hotfix] enzyme specific decoy DBs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- Dockerfile
- README.md
- environment.yml
- lib/NfcoreSchema.groovy
- main.nf
- nextflow.config
- nextflow_schema.json
> Merging template update 114

- main.nf
> Publish sdrf

- CHANGELOG.md
- bin/msstats_plfq.R
- main.nf
- nextflow.config
- nextflow_schema.json
Added support for user-specified contrasts in MSstats step.
> [Feature] msstats contrasts

- bin/create_trivial_design.py
> [FIX] exit code in design translation script

- bin/msstats_plfq.R
This code path is untested. We should add a test for it.
> [FIX] bug in userdefined contrasts
